/**
 * Response admission.
 *
 * Nothing may contribute evidence to a detection decision until it has passed through here.
 * This is the single most important false-positive control in the engine.
 *
 * The failure mode being prevented: a firewall that consistently blocks the break payload and
 * consistently passes the escape payload produces a perfectly stable, perfectly reproducible
 * difference. Every statistical test in the world will call that significant, because it IS
 * significant. It is just not evidence of server-side injection. The original Java
 * implementation had no gate at all: a null response was turned into the four bytes "null" and
 * fingerprinted as though it were a real response, so a reliable firewall drop was reported as
 * a high-confidence issue.
 *
 * A second, quieter failure mode: intermittent rate limiting. There the noise destroys the
 * feature set and the probe is silently judged uninteresting. Silence is more dangerous than
 * noise because the operator cannot see it. Soft failures are therefore counted and reported
 * as an explicit outcome, never folded into "nothing found".
 */

import {
  buildKeywordAutomaton,
  type KeywordAutomaton,
  matchPatterns,
} from "../response/keywords.ts";

import { type EngineResponse, type SendOutcome, type TransportFailure, header } from "./types.ts";

/** Why a response exists but must not contribute evidence. */
export type SoftFailReason =
  | "rate-limited"
  | "server-unavailable"
  | "bot-challenge"
  | "firewall-block";

export type Admission =
  | { readonly kind: "usable"; readonly response: EngineResponse }
  | {
      readonly kind: "soft-fail";
      readonly reason: SoftFailReason;
      /** Retained so the engine can learn the block fingerprint and so evidence can cite it. */
      readonly response: EngineResponse;
      /** Parsed from Retry-After when present. */
      readonly retryAfterMs?: number;
      /** Which fingerprint matched, for the operator-facing explanation. */
      readonly signal?: string;
    }
  | {
      readonly kind: "hard-fail";
      readonly failure: TransportFailure;
      readonly detail?: string;
    };

/**
 * Fingerprints that identify a block or challenge page on their own.
 *
 * Kept strong deliberately: each of these is vendor-specific boilerplate that essentially
 * never appears in application output. Anything more generic goes in the weak set below.
 */
const STRONG_FINGERPRINTS: readonly string[] = [
  "just a moment", // Cloudflare interstitial
  "error code: 1020", // Cloudflare firewall rule
  "cf-browser-verification",
  "checking your browser before accessing",
  "attention required! | cloudflare",
  "ddos protection by",
  "incapsula incident id", // Imperva
  "request unsuccessful. incapsula",
  "the requested url was rejected", // F5 BIG-IP ASM
  "px-captcha", // PerimeterX
  "perimeterx",
  "generated by wordfence",
  "this request has been blocked by",
  "your request has been blocked",
  "sucuri website firewall",
  "has been blocked by mod_security",
];

/**
 * Fingerprints that are only meaningful alongside a blocking status code. "access denied" and
 * "captcha" both occur legitimately in application content, so on their own they would suppress
 * real findings, which is a false NEGATIVE and worse than the noise they prevent.
 */
const WEAK_FINGERPRINTS: readonly string[] = [
  "captcha",
  "access denied",
  "web application firewall",
  "unusual traffic",
  "bot detected",
  "security policy",
];

/** Statuses that, combined with a weak fingerprint, indicate a block rather than app output. */
const BLOCK_STATUSES: ReadonlySet<number> = new Set([403, 406, 418]);

/** Response headers that identify an intermediary block on their own. */
const BLOCK_HEADERS: readonly string[] = [
  "cf-mitigated", // Cloudflare
  "x-iinfo", // Imperva
  "x-sucuri-block",
  "x-datadome", // DataDome
];

/**
 * How much of the response to inspect for a fingerprint.
 *
 * Block and challenge pages are small and put their identifying text near the top. Scanning
 * 8 KiB costs well under a millisecond even in QuickJS, where the measured rate is roughly
 * 103 microseconds per KiB.
 */
const FINGERPRINT_SCAN_BYTES = 8 * 1024;

let strongAutomaton: KeywordAutomaton | undefined;
let weakAutomaton: KeywordAutomaton | undefined;

export interface AdmissionOptions {
  /**
   * A captured block response to compare against by similarity, for firewalls whose block page
   * carries no recognisable text. Supplied by the engine once it has seen one.
   */
  readonly learnedBlock?: {
    readonly status: number;
    readonly bigrams: Int32Array;
    /** Cosine above which a response is considered the same block page. */
    readonly threshold: number;
  };
  /** Compares a response against the learned block page. Injected to avoid a scan dependency. */
  readonly similarityTo?: (response: EngineResponse) => number;
}

/**
 * Classify a send outcome for evidence eligibility.
 *
 * Ordering matters. Transport failure is checked first because there is no response to inspect.
 * Rate limiting is checked before firewall fingerprints because a 429 carrying a block page
 * should back off on the Retry-After rather than be recorded as a firewall signature.
 */
export function admit(
  outcome: SendOutcome,
  options: AdmissionOptions = {},
  nowMs?: number,
): Admission {
  if (outcome.kind === "failed") {
    return outcome.detail === undefined
      ? { kind: "hard-fail", failure: outcome.failure }
      : { kind: "hard-fail", failure: outcome.failure, detail: outcome.detail };
  }

  const response = outcome.response;

  if (response.status === 429) {
    const retryAfterMs = parseRetryAfter(header(response, "retry-after"), nowMs);
    return retryAfterMs === undefined
      ? { kind: "soft-fail", reason: "rate-limited", response, signal: "status 429" }
      : { kind: "soft-fail", reason: "rate-limited", response, retryAfterMs, signal: "status 429" };
  }

  for (const name of BLOCK_HEADERS) {
    if (header(response, name) !== undefined) {
      return {
        kind: "soft-fail",
        reason: "firewall-block",
        response,
        signal: `header ${name}`,
      };
    }
  }

  const scanTo = Math.min(
    response.raw.length,
    response.bodyStart + FINGERPRINT_SCAN_BYTES,
  );

  strongAutomaton ??= buildKeywordAutomaton(STRONG_FINGERPRINTS);
  const strong = matchPatterns(response.raw, response.bodyStart, scanTo, strongAutomaton);
  if (strong.size > 0) {
    const which = STRONG_FINGERPRINTS[[...strong][0]!]!;
    // A challenge invites the client to prove itself; a block simply refuses.
    const isChallenge =
      which.includes("just a moment") ||
      which.includes("checking your browser") ||
      which.includes("captcha") ||
      which.includes("verification");
    return {
      kind: "soft-fail",
      reason: isChallenge ? "bot-challenge" : "firewall-block",
      response,
      signal: which,
    };
  }

  // 503/502/504 with no challenge text is a genuinely unavailable upstream. Still unusable as
  // evidence, but it is an availability problem rather than a firewall signature, and the
  // distinction matters: one means slow down, the other means the payload is being filtered.
  if (response.status === 503 || response.status === 502 || response.status === 504) {
    const retryAfterMs = parseRetryAfter(header(response, "retry-after"), nowMs);
    return retryAfterMs === undefined
      ? {
          kind: "soft-fail",
          reason: "server-unavailable",
          response,
          signal: `status ${response.status}`,
        }
      : {
          kind: "soft-fail",
          reason: "server-unavailable",
          response,
          retryAfterMs,
          signal: `status ${response.status}`,
        };
  }

  if (BLOCK_STATUSES.has(response.status)) {
    weakAutomaton ??= buildKeywordAutomaton(WEAK_FINGERPRINTS);
    const weak = matchPatterns(response.raw, response.bodyStart, scanTo, weakAutomaton);
    if (weak.size > 0) {
      return {
        kind: "soft-fail",
        reason: "firewall-block",
        response,
        signal: `status ${response.status} with ${WEAK_FINGERPRINTS[[...weak][0]!]!}`,
      };
    }
  }

  const learned = options.learnedBlock;
  const similarityTo = options.similarityTo;
  if (learned !== undefined && similarityTo !== undefined) {
    if (response.status === learned.status && similarityTo(response) >= learned.threshold) {
      return {
        kind: "soft-fail",
        reason: "firewall-block",
        response,
        signal: "matches learned block page",
      };
    }
  }

  return { kind: "usable", response };
}

/**
 * Parse a Retry-After header into milliseconds.
 *
 * Accepts both forms from RFC 9110: delta-seconds, and an HTTP-date. A date in the past yields
 * zero rather than a negative delay. Returns undefined for anything unparseable, so the caller
 * falls back to its own backoff schedule rather than trusting a malformed value.
 */
export function parseRetryAfter(
  value: string | undefined,
  nowMs?: number,
): number | undefined {
  if (value === undefined) return undefined;
  const trimmed = value.trim();
  if (trimmed === "") return undefined;

  if (/^\d+$/.test(trimmed)) {
    return clampDelay(Number.parseInt(trimmed, 10) * 1000);
  }

  // Every HTTP-date form in RFC 9110 begins with a three-letter day name. Requiring that
  // before handing the string to Date.parse matters, because Date.parse is lenient: in V8
  // it happily turns "-5" into an ancient date, which would otherwise be reported as a zero
  // delay and defeat the backoff entirely.
  if (!/^[A-Za-z]{3},? /.test(trimmed)) return undefined;

  const at = Date.parse(trimmed);
  if (Number.isNaN(at)) return undefined;
  const base = nowMs ?? Date.now();
  return clampDelay(at - base);
}

/**
 * Upper bound on any delay derived from a server-supplied header, one hour.
 *
 * Without this, a header of "99999999999999999999" becomes a delay of 1e23 milliseconds and
 * the engine waits effectively forever instead of reporting that the target has stopped
 * answering. A caller whose own budget is smaller should abort rather than sleep: a target
 * asking for an hour is telling you to come back another day, not to block the event loop.
 */
export const MAX_RETRY_AFTER_MS = 60 * 60 * 1000;

function clampDelay(ms: number): number {
  if (!Number.isFinite(ms)) return MAX_RETRY_AFTER_MS;
  return Math.min(MAX_RETRY_AFTER_MS, Math.max(0, ms));
}

/** Whether an admission can contribute to a detection decision. */
export function isUsable(admission: Admission): admission is {
  kind: "usable";
  response: EngineResponse;
} {
  return admission.kind === "usable";
}

/**
 * Running tally of admission outcomes for one probe pair or one parameter.
 *
 * The engine reports this alongside every verdict. A negative result accompanied by a high
 * soft-fail rate is not a negative result, it is a blinded measurement, and the operator has to
 * be told which one they are looking at.
 */
export interface AdmissionTally {
  usable: number;
  softFail: number;
  hardFail: number;
  readonly reasons: Map<SoftFailReason | TransportFailure, number>;
}

export function newTally(): AdmissionTally {
  return { usable: 0, softFail: 0, hardFail: 0, reasons: new Map() };
}

export function record(tally: AdmissionTally, admission: Admission): void {
  if (admission.kind === "usable") {
    tally.usable += 1;
    return;
  }
  const key = admission.kind === "soft-fail" ? admission.reason : admission.failure;
  tally.reasons.set(key, (tally.reasons.get(key) ?? 0) + 1);
  if (admission.kind === "soft-fail") tally.softFail += 1;
  else tally.hardFail += 1;
}

/**
 * Fraction of attempts that produced no usable response.
 *
 * Above roughly a third, a measurement should be abandoned and reported as blinded rather than
 * concluded. The threshold belongs to the caller because the right value differs between the
 * calibration phase and a confirmation loop.
 */
export function unusableRate(tally: AdmissionTally): number {
  const total = tally.usable + tally.softFail + tally.hardFail;
  return total === 0 ? 0 : (tally.softFail + tally.hardFail) / total;
}
